mysite/mysite/mysite/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
]

mysite/mysite/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('uploads/', include('uploads.urls',namespace='uploads')),
    path('main/',include('main.urls', namespace='main')),
]

mysite/mysite/mysite/uploads/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='uploads'
urlpatterns = [
    path('', views.index, name='index'),
]

mysite/mysite/mysite/main/models.py
from django.db import models

# Create your models here.

mysite/mysite/mysite/uploads/models.py
from django.db import models

# Create your models here.

mysite/mysite/mysite/uploads/forms.py
from django import forms
from datetime import datetime, timedelta

types = [('headcount', 'Head Count'), ('empleado', 'Empleados'),\
(u'desempeño', u'Desempeño'), ('vacante', 'Vacante'), ('potencial', 'Potencial'),\
('hogan', 'Hogan')
]

months = {
    1: 'Enero',\
    2: 'Febrero',\
    3: 'Marzo',\
    4: 'Abril',\
    5: 'Mayo',\
    6: 'Junio',\
    7: 'Julio',\
    8: 'Agosto',\
    9: 'Setiembre',\
    10: 'Octubre',\
    11: 'Noviembre',\
    12: 'Diciembre',\
}
years = [(datetime.today()+timedelta(days=30 * i)).year for i in range(1,13)]
month = [months[(datetime.today()+timedelta(days=30 * i)).month] for i in range(1,13)]
periodos = [(month[i].lower(), month[i]+' '+str(years[i])) for i in range(11)]

class UploadFileForm(forms.Form):
    tipo = forms.ChoiceField(choices = types,widget=forms.Select(choices = types))
    periodo = forms.ChoiceField(choices = periodos, widget=forms.Select(choices=types))
    archivo = forms.FileField()

mysite/mysite/mysite/main/views.py
from django.shortcuts import render
from django.template import loader
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    template = loader.get_template("main/index.html")
    return render(request, 'main/index.html')

@login_required
def get_user_profile(request,username):
    user = User.objects.get(username=username)
    #return render(request, 'uploads')

mysite/mysite/mysite/uploads/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from .forms import UploadFileForm
from .store_file import store_file_to_azure
from .logic import handle_uploaded_file
from .charts import charts, datasummary
import os
from datetime import datetime, timedelta

@login_required
def index(request):
    template = loader.get_template("uploads/index.html")
    context = {'show_upload_status': False, 'uploaded_file_url': False, 'form': UploadFileForm()}

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            fs = FileSystemStorage()
            filename = fs.save('{}.xlsx'.format('_'.join([request.POST['tipo'],str(request.user),\
             request.POST['periodo']])),request.FILES['archivo'])
            url = fs.url(filename)

            upload_file_handle, errors = handle_uploaded_file(request.FILES['archivo'],request.POST['tipo'], ' '.join([str(request.POST['periodo']).title(),str(datetime.today().year)]))

            if upload_file_handle:

                store_file_to_azure(url)

                script, div = charts(request.FILES['archivo'], request.POST['tipo'])

                summary = datasummary(request.FILES['archivo'])

                context['resumen'] = summary
                context['show_upload_status'] = True
                context['uploaded_file_success'] = True
                context['script'] = script
                context['div'] = div

                return render(request, 'uploads/index.html', context)
            else:
                errors_list = '<ul style="background-color: white !important"> '
                for key, value in errors.items():
                    if not value:
                        errors_list += '<li> ' + key + '</li>'
                errors_list += '</ul>'
                context['show_upload_status'] = True
                context['uploaded_file_success'] = False
                context['error_list'] = errors_list
                os.remove(url)
                return render(request, 'uploads/index.html', context)
        else:
            return HttpResponse("Form not valid")
    else:
        return render(request, 'uploads/index.html', context)

@login_required
def get_user_profile(request,username):
    user = User.objects.get(username=username)
    return render(request, 'uploads')

mysite/mysite/mysite/main/templates/main/index.html
{% extends 'base.html' %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />

{% block content%}
<div class = "links">
  <h2> Enlaces de interés </h2>
  <div>
    <a href="{% url 'uploads:index' %}">Carga de Datos</a>
  </div>
  <div>
    <a >Visualizador</a>
  </div>
  <div>
    <a href="{% static 'main/media/Plantillas_Carga_Excel.zip' %}"> Descarga de Plantillas </a>
  </div>
</div>
<div class = 'views'>
  <h2> Bienvenido! </h2>
</div>
{% endblock %}

mysite/mysite/mysite/uploads/templates/base.html
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.pydata.org/bokeh/release/bokeh-0.13.0.min.css" rel="stylesheet" type="text/css">
    <script src="https://cdn.pydata.org/bokeh/release/bokeh-0.13.0.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Markazi+Text" rel="stylesheet">
</head>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'base/style.css' %}" />
<body>
{% if user.is_authenticated %}
  <ul>
     <li class="username_li">User: {{ user.get_username }}</li>
     <li class="logout_li"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  </ul>

  {% block content %}{% endblock content %}
{% endif %}

mysite/mysite/mysite/uploads/templates/uploads/index.html
{% extends "base.html" %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'uploads/style.css' %}" />
{% block content %}

<h2> Formulario de carga de datos </h2>

<div class='form_container'>
  <form method="post" enctype="multipart/form-data" style='display:inline-block'>
    {% csrf_token %}
    <table class = 'form-input'>
      {{ form.as_table }}
    </table>
    <button type="submit" >Upload</button>
  </form>
</div>
  {% if show_upload_status %}
    {% if uploaded_file_success %}
      <p>Carga exitosa</p>
      <div class='dataframe_container'>
        {{ resumen|safe }}
      </div>
      <p></p>
      <div class='plots_container'>
        {{ div|safe }}
        {{ script|safe }}
      </div>
    {% else %}
      <p>Error en carga de archivo: {{ error_list|safe }}</p>
    {% endif %}
  {% endif %}
</body>

{% endblock %}